<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Demo project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="static/libs/dist/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="static/css/dist/fonts.css">
    <link rel="stylesheet" href="static/css/dist/index.css">
    <script type="text/javascript">
      var yOSON = {
      	"module": "home",
      	"controller": "index",
      	"action": "index",
      	"baseHost": "",
      	"statHost": "",
      	"eHost": "",
      	"statVers": "",
      	"AppCore": {},
      	"AppSandbox": {},
      	"AppSchema": {
      		"modules": {},
      			"requires": {}
      	}
      };
    </script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="active"><a>Artistas</a></li>
          <li><a>Albunes5</a></li>
          <li><a>Letras</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="col-xs-6">
        <div class="row">
          <h4>Discography</h4>
          <ul>
            <li>
              <div class="name_disc">Surprise Without Flaws</div>
              <div class="point">·</div>
              <div class="year">2015</div>
              <div class="options"><a class="listen" href="#">listen | </a><a class="buy" href="#">buy</a></div>
            </li>
            <li>
              <div class="name_disc">Surprise Without Flaws</div>
              <div class="point">·</div>
              <div class="year">2015</div>
              <div class="options"><a class="listen" href="#">listen | </a><a class="buy" href="#">buy</a></div>
            </li>
            <li>
              <div class="name_disc">Surprise Without Flaws</div>
              <div class="point">·</div>
              <div class="year">2015</div>
              <div class="options"><a class="listen" href="#">listen | </a><a class="buy" href="#">buy</a></div>
            </li>
            <li>
              <div class="name_disc">Surprise Without Flaws</div>
              <div class="point">·</div>
              <div class="year">2015</div>
              <div class="options"><a class="listen" href="#">listen | </a><a class="buy" href="#">buy</a></div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="row">
          <h4>Now Playing</h4>
          <h5>Surprise Without Flaws</h5>
          <p>01. Clouds In The Forest</p>
        </div>
        <div class="row">
          <div class="progress">
            <div class="progress-bar" role="progress-bar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">60%</span></div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-5">
            <button class="btn btn-default pull-right" type="button"><span class="glyphicon glyphicon-step-backward"></span></button>
          </div>
          <div class="col-xs-2">
            <button class="btn btn-default center-block" type="button"><span class="glyphicon glyphicon-pause"></span></button>
          </div>
          <div class="col-xs-5"> 
            <button class="btn btn-default pull-left" type="button"><span class="glyphicon glyphicon-step-forward"></span></button>
          </div>
        </div>
        <div class="row">
          <h5>Surprise Without Flaws</h5>
        </div>
        <div class="row">
          <ul>
            <li>
              <div class="name_disc">1. Clouds In The Forest</div>
              <div class="options"><a class="listen" href="#">3:20 </a></div>
            </li>
            <li>
              <div class="name_disc">2. Clouds In The Forest</div>
              <div class="options"><a class="listen" href="#">3:20 </a></div>
            </li>
            <li>
              <div class="name_disc">3. Clouds In The Forest</div>
              <div class="options"><a class="listen" href="#">3:20 </a></div>
            </li>
            <li>
              <div class="name_disc">4. Clouds In The Forest</div>
              <div class="options"><a class="listen" href="#">3:20 </a></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </body>
  <script src="static/libs/dist/jquery/dist/jquery.js" type="text/javascript"></script>
  <script src="static/libs/dist/yosonjs/dist/yoson.js" type="text/javascript"></script>
  <script src="static/js/dist/scripts/index.js" type="text/javascript"></script>
  <script src="static/js/dist/libs/yosonjs-utils.js" type="text/javascript"></script>
</html>