<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Demo project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo _STATIC_ ?>/libs/dist/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="<?php echo _STATIC_ ?>/css/dist/fonts.css">
    <link rel="stylesheet" href="<?php echo _STATIC_ ?>/css/dist/<?php echo _MODULE_ ?>/<?php echo _VIEW_ ?>.css">
    <script type="text/javascript">
      var yOSON = {
        "module": "<?php echo _MODULE_ ?>",
        "controller": "<?php echo _CONTROLLER_ ?>",
        "action": "<?php echo _VIEW_ ?>",
        "baseHost": "",
        "statHost": "",
        "eHost": "",
        "statVers": "",
        "AppCore": {},
        "AppSandbox": {},
        "AppSchema": {
          "modules": {},
            "requires": {}
        }
      };
    </script>
  </head>
  <body>
    <body>   
      <header>
        <nav class="navbar navbar-default">
          <div class="container">
            <ul class="nav navbar-nav">
              <li class="active"><a>logo</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a>Ipsum</a></li>
              <li><a>Consectetur</a></li>
              <li><a>Aliqua</a></li>
              <li><a>Laborum</a></li>
            </ul>
          </div>
        </nav>
      </header>
      <main>
        <div class="container inner">
          <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Library</a></li>
            <li><a class="active" href="#">Data</a></li>
          </ol>
          <div class="jumbotron">
            <h1>Hello, world!</h1>
          </div>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            
          </p>
          <nav aria-label="Page navigation">
            <ul class="pagination">
              <li><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
              <li><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
            </ul>
          </nav>
        </div>
      </main>
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              <h5>footer</h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</p>
            </div>
            <div class="col-xs-6">
              <h5>Links</h5>
              <ul>
                <li class="active"><a>logo</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">© 2014 Copyright Text<a href="#">More links</a></div>
        </div>
      </footer>
    </body>
  </body>
  <script src="<?php echo _STATIC_ ?>/libs/dist/jquery/dist/jquery.js" type="text/javascript"></script>
  <script src="<?php echo _STATIC_ ?>/libs/dist/yosonjs/dist/yoson.js" type="text/javascript"></script>
  <script src="<?php echo _STATIC_ ?>/js/dist/scripts/<?php echo _MODULE_ ?>/<?php echo _VIEW_ ?>.js" type="text/javascript"></script>
  <script src="<?php echo _STATIC_ ?>/js/dist/libs/yosonjs-utils.js" type="text/javascript"></script>
</html>