<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Demo project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo $this->staticUrl ?>/libs/dist/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="<?php echo $this->staticUrl ?>/css/dist/fonts.css">
    <link rel="stylesheet" href="<?php echo $this->staticUrl ?>/css/dist/<?php echo $this->module ?>/<?php echo $this->action ?>.css">
    <script type="text/javascript">
      var yOSON = {
        "module": "<?php echo $this->module ?>",
        "controller": "<?php echo $this->controller ?>",
        "action": "<?php echo $this->action ?>",
        "baseHost": "",
        "statHost": "",
        "eHost": "",
        "statVers": "",
        "AppCore": {},
        "AppSandbox": {},
        "AppSchema": {
          "modules": {},
            "requires": {}
        }
      };
    </script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="active"><a>Login</a></li>
        </ul>
      </div>
    </nav>
    <p>hola mundo 2</p>
    <div class="container">
      <fb:login-button scope="public_profile,email" onlogin="checkLoginState();"></fb:login-button>
    </div>
  </body>
  <script src="<?php echo $this->staticUrl ?>/libs/dist/jquery/dist/jquery.js" type="text/javascript"></script>
  <script src="<?php echo $this->staticUrl ?>/libs/dist/yosonjs/dist/yoson.js" type="text/javascript"></script>
  <script src="<?php echo $this->staticUrl ?>/js/dist/scripts/<?php echo $this->module ?>/<?php echo $this->action ?>.js" type="text/javascript"></script>
  <script src="<?php echo $this->staticUrl ?>/js/dist/libs/yosonjs-utils.js" type="text/javascript"></script>
</html>